name: Release ledfx-dev zip

on:
  push:
    branches:
      - main
    paths:
      - 'ledfx-dev/ledfx.code-workspace'
      - 'ledfx-dev/ledfx.setup.js'
      - 'ledfx-dev/readme.md'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up zip
        run: |
          zip -r ledfx-dev.zip ledfx-dev

      - name: Get version
        id: get_version
        run: |
          echo "::set-output name=version::$(date +'%Y.%m.%d-%H%M%S')"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ledfx-dev-${{ steps.get_version.outputs.version }}
          name: ledfx-dev release ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
          files: ledfx-dev.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
